ADAMsteps: 501
n_steps: 500
batch_size: 50
res_level: 5
scaling_factor: 0.0005
# rescale factor
factor: 2
# Data Source
filenamesX: "/home/thelfer1/scr4_tedwar42/thelfer1/high_end_data/outputXdata_level{res_level}_step*.dat"
# Restarting
restart: False
file_path: "model_epoch_counter_0000000049_data_time_1718669354.pth"
lambda_fac: 0.0
